Numpy

In [14]:
# Create a NumPy array and perform various operations like addition, subtraction, multiplication, and division.
import numpy as np

arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])

#addiion of two arrays
add = arr1 + arr2
print(f"Addition: {add}")

#substraction of two arrays
sub = arr1 - arr2
print(f"Subtraction: {sub}")

#multiplication of two arrays
multiply = arr1 * arr2
print(f"Multiplication: {multiply}")

arr3 = 2
arr4 = 4
#division of two arrays
division = arr3 / arr4
print(f"Division: {division}")

Addition: [ 3  7 11 15 19]
Subtraction: [-1 -1 -1 -1 -1]
Multiplication: [ 2 12 30 56 90]
Division: 0.5


In [32]:
#Explore indexing and slicing to access specific elements or subsets of the array.

#indexing
array = np.array([10,20,30,40,50,60,70,80])
print("indexing", array[0])
print("indexing", array[2])

#slicing
print("slicing", array[1:3])

# Slicing with a step
print("slicing with steps", array[0:2:4])

# negative indexing
print("negative ind", array[-1])

#multi_dimensional array
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

print("number", array_2d[0,2])

#slicing in 2d array
array_2d = np.array([[1,2,3,33,22,55],
                     [4,5,6,88,22,74],
                     [7,8,9,73,92,92]])

print("number", array_2d[0:3, 1:3])

indexing 10
indexing 30
slicing [20 30]
slicing with steps [10]
negative ind 80
number 3
number [[2 3]
 [5 6]
 [8 9]]


In [37]:
#Practice reshaping arrays and transposing matrices.
import numpy as np
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])
print("1D Array:")
print(array_1d)
# Reshape the 1D array to a 2D array (2 rows, 3 columns)
array_2d = array_1d.reshape((2, 3))
print("\nReshaped 2D Array (2x3):")
print(array_2d)
# Transpose the 2D array
transposed_array = array_2d.T
print("\nTransposed Array:")
print(transposed_array)
# Reshape the original array to a 3D array (1x2x3)
array_3d = array_1d.reshape((1, 2, 3))
print("\n3D Array (1x2x3):")
print(array_3d)
# Flatten the 2D array back to a 1D array
flattened_array = array_2d.flatten()
print("\nFlattened Array:")
print(flattened_array)

# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Original Matrix:")
print(matrix)
# Transpose using np.transpose()
transposed_matrix_np = np.transpose(matrix)
print("\nTransposed Matrix using np.transpose():")
print(transposed_matrix_np)



1D Array:
[1 2 3 4 5 6]

Reshaped 2D Array (2x3):
[[1 2 3]
 [4 5 6]]

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]

3D Array (1x2x3):
[[[1 2 3]
  [4 5 6]]]

Flattened Array:
[1 2 3 4 5 6]
Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix using np.transpose():
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [36]:
#Use NumPy functions to calculate statistics like mean, median, standard deviation, and variance.

data = np.array([101, 2, 32, 40, 22, 77, 70, 81, 38, 19])
                
# Calculate the mean
mean_val = np.mean(data)
print("Mean:", mean_val)

# Calculate the median
median_val = np.median(data)
print("Median:", median_val)

# Calculate the standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Calculate the variance
variance_val = np.var(data)
print("Variance:", variance_val)


Mean: 48.2
Median: 39.0
Standard Deviation: 30.455869713406642
Variance: 927.5600000000001


In [40]:
# Create arrays with different data types (e.g., int, float, bool, str).
# Concatenate arrays.
# Sort arrays in ascending or descending order.

# Integer array
int_array = np.array([2,3,5,6])
print("Integer Array:", int_array)

# Float array
float_array = np.array([1.2, 2.33, 3.223, 4.44, 5.115])
print("Float Array:", float_array)

# Boolean array
bool_array = np.array([True, False, True, False])
print("Boolean Array:", bool_array)

# String array
str_array = np.array(["car", "ship", "bike"])
print("String Array:", str_array)

#concatenate array
conc_array = np.concatenate((int_array, float_array))
print("int+float concatenated array: ", conc_array)

#sorting array
sort_int_array = np.sort(int_array)
print("Sorted Integer Array (Ascending):", sort_int_array)


sort_str_array = np.sort(str_array)
print("Sorted String Array (Ascending):", sort_str_array)

Integer Array: [2 3 5 6]
Float Array: [1.2   2.33  3.223 4.44  5.115]
Boolean Array: [ True False  True False]
String Array: ['car' 'ship' 'bike']
int+float concatenated array:  [2.    3.    5.    6.    1.2   2.33  3.223 4.44  5.115]
Sorted Integer Array (Ascending): [2 3 5 6]
Sorted String Array (Ascending): ['bike' 'car' 'ship']


Pandas

In [2]:
# Load data from various sources (e.g., CSV, Excel, JSON).

import pandas as pd

df_csv = pd.read_csv('Spotify.csv')
print(df_csv.head())

                            track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams  in_apple_playlists  ...  key   mode  \
0                147  141381703                  4

In [8]:
# Load Excel file
df_excel = pd.read_excel('FSI-2023-DOWNLOAD.xlsx')
print(df_excel.head())


                     Country  Year Rank  Total  S1: Demographic Pressures  \
0                    Somalia  2023  1st  111.9                       10.0   
1                      Yemen  2023  2nd  108.9                        9.6   
2                South Sudan  2023  3rd  108.5                        9.7   
3  Congo Democratic Republic  2023  4th  107.2                        9.7   
4                      Syria  2023  5th  107.1                        7.4   

   S2: Refugees and IDPs  C3: Group Grievance  \
0                    9.0                  8.7   
1                    9.6                  8.8   
2                   10.0                  8.6   
3                    9.8                  9.4   
4                    9.1                  9.1   

   E3: Human Flight and Brain Drain  E2: Economic Inequality  E1: Economy  \
0                               8.6                      9.1          9.5   
1                               6.4                      7.9          9.9   
2          

In [9]:
# Load JSON file
df_json = pd.read_json('employees.json')
print(df_json.head())


                           103         104         101
Employee ID                103         104         101
Name                     Ahmed        Eman       Alice
Position     Head of Marketing  HR Manager         I.T
Salary              99999999.0    226262.0     33733.0
Department   Central Marketing          HR  Production


In [10]:
df_csv = pd.read_csv('Spotify.csv')
print(df_csv.head())

                            track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams  in_apple_playlists  ...  key   mode  \
0                147  141381703                  4

In [14]:
# 1. Checking the Shape
# Get the shape
print("Shape of the DataFrame:", df.shape)

Shape of the DataFrame: (953, 25)


In [15]:
# Check data types
print("Data Types of the DataFrame:")
print(df.dtypes)

Data Types of the DataFrame:
track_name              object
artist(s)_name          object
artist_count             int64
released_year            int64
released_month           int64
released_day             int64
in_spotify_playlists     int64
in_spotify_charts        int64
streams                 object
in_apple_playlists       int64
in_apple_charts          int64
in_deezer_playlists     object
in_deezer_charts         int64
in_shazam_charts        object
bpm                      int64
key                     object
mode                    object
danceability_%           int64
valence_%                int64
energy_%                 int64
acousticness_%           int64
instrumentalness_%       int64
liveness_%               int64
speechiness_%            int64
cover_url               object
dtype: object


In [16]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing Values in each column:")
print(missing_values[missing_values > 0])  # Only show columns with missing values

Missing Values in each column:
in_shazam_charts    50
key                 95
dtype: int64


In [17]:
# Summarize the data using descriptive statistics.
print("Summary Statistics:")
print(df.describe())

Summary Statistics:
       artist_count  released_year  released_month  released_day  \
count    953.000000     953.000000      953.000000    953.000000   
mean       1.556139    2018.238195        6.033578     13.930745   
std        0.893044      11.116218        3.566435      9.201949   
min        1.000000    1930.000000        1.000000      1.000000   
25%        1.000000    2020.000000        3.000000      6.000000   
50%        1.000000    2022.000000        6.000000     13.000000   
75%        2.000000    2022.000000        9.000000     22.000000   
max        8.000000    2023.000000       12.000000     31.000000   

       in_spotify_playlists  in_spotify_charts  in_apple_playlists  \
count            953.000000         953.000000          953.000000   
mean            5200.124869          12.009444           67.812172   
std             7897.608990          19.575992           86.441493   
min               31.000000           0.000000            0.000000   
25%              

In [32]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('Spotify.csv')
print(df.head())
# Selecting specific columns
selected_columns = df[['released_year', 'in_spotify_playlists']]
print(selected_columns)


                            track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams  in_apple_playlists  ...  key   mode  \
0                147  141381703                  4

In [33]:
# Filtering rows where 'column1' > 10
filtered_rows = df[df['released_day'] > 10]
print(filtered_rows)


                              track_name      artist(s)_name  artist_count  \
0    Seven (feat. Latto) (Explicit Ver.)    Latto, Jung Kook             2   
1                                   LALA         Myke Towers             1   
2                                vampire      Olivia Rodrigo             1   
3                           Cruel Summer        Taylor Swift             1   
4                         WHERE SHE GOES           Bad Bunny             1   
..                                   ...                 ...           ...   
941        Would've, Could've, Should've        Taylor Swift             1   
944                        The Astronaut                 Jin             1   
947                        The Great War        Taylor Swift             1   
949            Bigger Than The Whole Sky        Taylor Swift             1   
951                        En La De Ella  Feid, Sech, Jhayco             3   

     released_year  released_month  released_day  in_spotify_pl

In [34]:
# Selecting rows where 'column1' > 10 and only the columns 'column1' and 'column3'
filtered_selection = df.loc[df['in_apple_playlists'] > 10, ['in_spotify_charts', 'in_spotify_playlists']]
print(filtered_selection)


     in_spotify_charts  in_spotify_playlists
0                  147                   553
1                   48                  1474
2                  113                  1397
3                  100                  7858
4                   50                  3133
..                 ...                   ...
937                  0                  1794
939                  2                  1652
948                  0                   953
951                  0                  1320
952                  2                   782

[754 rows x 2 columns]


In [35]:
# Using iloc to select the first 5 rows
first_five_rows = df.iloc[:5]
print(first_five_rows)

                            track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams  in_apple_playlists  ...  key   mode  \
0                147  141381703                  4